### ISSUE TITLE
运行闪退

### ISSUE THREAD

**Issue by lowy** [linuxdeepin/deepin-system-monitor#10]
编译环境 Debian testing x86_64 Linux 4.12.0-1-amd64
$ ./deepin-system-monitor
"deepin-system-monitor" can not find qm files
Ethernet link detected
[1]    2243 segmentation fault  ./deepin-system-monitor

**Comment by lowy** [comment]
![deepinscreenshot_xfce4-terminal_20170909144937](https://user-images.githubusercontent.com/6565177/30237884-3aa75fa4-956e-11e7-9d15-47d9a868f20e.png)

**Comment by lowy** [comment]
![deepinscreenshot_xfce4-terminal_20170909145611](https://user-images.githubusercontent.com/6565177/30237926-13f4dac0-956f-11e7-8165-0fcd25c68f92.png)

**Comment by manateelazycat** [comment]
系统监视器编译的步骤是：
* mkdir build
* cd build
* qmake ..
* make
* sudo setcap cap_kill,cap_net_raw,cap_dac_read_search,cap_sys_ptrace+ep ./deepin-system-monitor

最后一步，需要用　setcap 赋予　deepin-system-monitor 权限，才能正常启动，你是否按照Readme里面的调用了　setcap 以后才启动的？

我看到你启动后有　Error: opening handler for device enp2s0 的错误，看着像系统监视器没有权限访问网络设备
