### ISSUE TITLE
Not recognizing spotify as an application

### ISSUE THREAD

**Issue by igormp** [linuxdeepin/deepin-system-monitor#13]
Even though Spotify is listed under running processes, it's not presented in the Applications tab, as seen in the picture bellow.
![Deepin system monitor](https://user-images.githubusercontent.com/5247904/38786921-42d9ffee-4101-11e8-8967-13648341ef44.png)

Currently running on version 1.4.3-1

**Comment by z966768** [comment]
please try the latest version
