### ISSUE TITLE
期待功能完善

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/deepin-system-monitor#16]
要是有刷新时间设置就好了，默认的刷新时间不够快。
其实gnome-system-monitor在功能上蛮好，但我用着发现它磁盘读取太高...
而且deepin-system-monitor确实好看呀

**Comment by z966768** [comment]
首先,感谢你的使用,现在新版的系统监视器也做了不少修改,关于你提的需求,我们会进行评估.谢谢
