### ISSUE TITLE
why on arch doesn't show decimals ?? 

### ISSUE THREAD

**Issue by elswerky** [linuxdeepin/deepin-system-monitor#18]
Why when i use deepin system monitor on arch or manjaro ,  

in Memory Usage it doesn't show decimals 

for example if i have 5.80 GB ram it read it 5 GB ram 
and if 1.95 GB  ram is used it read it 1 GB ram used 

but the graph beside it shows it correctly 
![deepinscreenshot_select-area_20180602172351](https://user-images.githubusercontent.com/26687459/40877960-cd34eb9c-6689-11e8-8e5b-e261d66b5833.png)

**Comment by z966768** [comment]
The new version has been modified and now it will display a decimal
