### ISSUE TITLE
[Improvement] Make it lighter

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-system-monitor#19]
It seems that Deepin System Monitor uses quite some amount of CPU.
It would be great if you guys could make it more lighter.

**Comment by z966768** [comment]
it seems like the same problem [30](https://github.com/linuxdeepin/deepin-system-monitor/issues/30).please try
 the latest version, we have do some work

**Comment by YutianGe** [comment]
Try it out with the latest version

**Comment by YutianGe** [comment]
Try it out with the latest version

**Comment by YutianGe** [comment]
Try it out with the latest version

**Comment by YutianGe** [comment]
Try it out with the latest version

**Comment by YutianGe** [comment]
Try it out with the latest version

**Comment by YutianGe** [comment]
可以尝试使用最新版本

**Comment by YutianGe** [comment]
You can try the latest version
