### ISSUE TITLE
Download speed  & Disk write is not showing correctly

### ISSUE THREAD

**Issue by AInoob** [linuxdeepin/deepin-system-monitor#20]
Hello there,
So the application download speed is not showing correctly.
And the Disk write is in MB/s, which is not correct either.
![deepinscreenshot_select-area_20180922232924](https://user-images.githubusercontent.com/7615460/45924868-7bcf1500-bebf-11e8-81b5-9d0ce3c210dc.png)

**Comment by z966768** [comment]
Please use the latest version and welcome feedback

**Comment by LeiYu-uniontech** [comment]
Please use the latest version and welcome feedback

**Comment by LeiYu-uniontech** [comment]
You can try the latest version

**Comment by YutianGe** [comment]
You can try using the latest version and welcome feedback

**Comment by YutianGe** [comment]
You can try using the latest version and welcome feedback
