### ISSUE TITLE
在Arch DDE15.8环境下，右键进程属性对话框的右上角关闭按钮位置错误

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/deepin-system-monitor#21]
![Uploading 深度截图_deepin-system-monitor_20181107204138.png…]()

**Comment by xiaoc-arch** [comment]
![_deepin-system-monitor_20181107204138](https://user-images.githubusercontent.com/44838410/48132687-62e3bd00-e2cf-11e8-82f7-2bfc4419d4ad.png)

**Comment by xiaoc-arch** [comment]
![_deepin-system-monitor_20190212123135](https://user-images.githubusercontent.com/44838410/52611874-8025ba00-2ec2-11e9-8fee-b934eb535750.png)
在Arch DDE15.9.1环境下，右键进程属性对话框的右上角关闭按钮位置错误,这个bug提交n很久了，没人理吗。。。。。。。。。。

**Comment by hillwoodroc** [comment]
这个问题应该问肥猫。

**Comment by z966768** [comment]
Both the system and the application are too old, please use the new version
