### ISSUE TITLE
dtkwidget dtkbase 在哪儿能够找到？

### ISSUE THREAD

**Issue by noparkinghere** [linuxdeepin/deepin-system-monitor#3]
编译时，缺少 dtkwidget 等 development package.

**Comment by rekols** [comment]
in deepin, you can
sudo apt install libdtkbase-dev libdtkwidget-dev libdtkutil-dev

**Comment by noparkinghere** [comment]
In deepin , I needn't install these software. I have several computers and find that many softwares are great in deepin, so I want to install them in a computer of ubuntu.

**Comment by zhtengw** [comment]
@noparkinghere dtkbase dtkwidget are parts of deepin-tool-kit(https://github.com/linuxdeepin/deepin-tool-kit).

**Comment by manateelazycat** [comment]
@noparkinghere I use dtk git version, you can compile git deepin-tool-kit first.
