### ISSUE TITLE
CPU消耗太多

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/deepin-system-monitor#30]
我的系统: deepin15.10.1 CPU: AMD A8 7410
在我的电脑上deepin-system-monitor打开要消耗大约20%的CPU，这显然太高了，需要优化
gnome-system-monitor 只消耗大概1%~3%的CPU
![图片](https://user-images.githubusercontent.com/12093211/59080496-9517d480-891b-11e9-980f-906f49a7c33a.png)

**Comment by z966768** [comment]
The CPU occupancy problem has been optimized，you can try the latest version

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
