### ISSUE TITLE
deepin-system-monitor gets randomly Segmentation fault error!

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/deepin-system-monitor#31]
deepin-system-monitor gets  randomly Segmentation fault error!
![deepin-screen-recorder_dde-desktop_20190621162048](https://user-images.githubusercontent.com/52075807/59925757-7815f200-9441-11e9-8540-f09be6e6a531.gif)

**Comment by BLumia** [comment]
Did you got `systemd-coredump` installed? A coredump stacktrace would be helpful for debug this issue.

**Comment by Mark-AAAA** [comment]
I have some file in /var/lib/systemd/coredump but not for deepin system monitor.

**Comment by Mark-AAAA** [comment]
nobody cares, bye.
