### ISSUE TITLE
MB up and Down (History requested)

### ISSUE THREAD

**Issue by bksubhuti** [linuxdeepin/deepin-system-monitor#33]
It would be good to see System monitor to show mb up and down history rather than just current speed.

**Comment by z966768** [comment]
The network has historical records, which module do you refer to?

**Comment by bksubhuti** [comment]
I'm sorry but I'm no longer on deepin.  I use kde now.  However, as far as I remember , when I used deepin system monitor , I could see the bandwidth being used but not the total data used , like mb or gb up and down.  It is important to know this if you are paying for mb by a cellular connection.
