### ISSUE TITLE
Task bar widget

### ISSUE THREAD

**Issue by richardaum** [linuxdeepin/deepin-system-monitor#41]
Is there any option to display a widget on task bar, similar to Ubuntu 18?

![image](https://user-images.githubusercontent.com/2018161/82401029-14b88980-9a2f-11ea-8532-9b76a3d61449.png)

**Comment by z966768** [comment]
thank you for your idea,we will think about it

**Comment by z966768** [comment]
This feature will not be implemented in the short term because it does not match the overall design.sorry about that,and thank you for your comments
