### ISSUE TITLE
QT 5.14 cpustat info not draw

### ISSUE THREAD

**Issue by edgarlopez** [linuxdeepin/deepin-system-monitor#43]
Error: QObject::connect: Cannot queue arguments of type 'QList<qreal>'
(Make sure 'QList<qreal>' is registered using qRegisterMetaType()

Fix: add qRegisterMetaType in files

compact_cpu_monitor.cpp
`qRegisterMetaType<QList<qreal>>("CpuStatInfo");
connect(smo->jobInstance(), &StatsCollector::cpuStatInfoUpdated,
            this, &CompactCpuMonitor::updateStatus);
`

cpu_monitor.cpp
`    qRegisterMetaType<QList<qreal>>("CpuStatInfo");
    connect(smo->jobInstance(), &StatsCollector::cpuStatInfoUpdated,
            this, &CpuMonitor::updateStatus);`

**Comment by z966768** [comment]
QList<qreal> has been registered in main function

**Comment by edgarlopez** [comment]
Still not working version 5.6.21

![Screen Capture_select-area_20200904051628](https://user-images.githubusercontent.com/5170916/92238321-d6c06380-ee6d-11ea-9148-946a82ae3cf1.png)

**Comment by Cardellino** [comment]
Even with the version deepin-system-monitor-5.8.0.1 does not work.
![Screen Capture_select-area_20201103091904](https://user-images.githubusercontent.com/73848158/97962763-1fd15d00-1db6-11eb-9d7f-069f337f227e.png)

**Comment by z966768** [comment]
This should be a signal transmission problem, currently only appears in arch linux, and architecture adjustments will be made later

**Comment by openarun** [comment]
https://github.com/UbuntuDDE/bugs/issues/33

**Comment by elopezintqd** [comment]
Fix:   add `QList<qreal>` text in to qRegisterMetaType

```
int main(int argc, char *argv[])
{
    util::installCrashHandler();
    util::common::init_seed();
    PERF_PRINT_BEGIN("POINT-01", "");

    qRegisterMetaType<QList<qreal>>("QList<qreal>");

    Application::setAttribute(Qt::AA_UseHighDpiPixmaps, true);

    Application app(argc, argv);
    app.setAutoActivateWindows(true);
```

compile **Archlinux qt5 5.15.2** works for me!!
