### ISSUE TITLE
cpu占用曲线不显示问题

### ISSUE THREAD

**Issue by Scfy-Code** [linuxdeepin/deepin-system-monitor#44]
![深度截图_dde-desktop_20200909215752](https://user-images.githubusercontent.com/42332005/92608474-ff21e500-f2e7-11ea-9a02-1945f9abb3d7.png)
系统：arch+dde桌面+deepin全家桶
描述：系统监视器在紧凑模式下，左上角的cpu曲占用曲线不会绘制。

**Comment by z966768** [comment]
已知问题，请关注后续版本

**Comment by xmuli** [comment]
see [# 297](https://github.com/linuxdeepin/dde-dock/issues/297)
