### ISSUE TITLE
./deepin-system-monitor: relocation error

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/deepin-system-monitor#5]
./deepin-system-monitor: relocation error: /usr/lib/x86_64-linux-gnu/libdtkwidget.so.1: symbol _ZN27QPlatformIntegrationFactory4keysERK7QString, version Qt_5 not defined in file libQt5Gui.so.5 with link time reference

**Comment by manateelazycat** [comment]
You need install qtbase5-private-dev, it's include header file:

/usr/include/x86_64-linux-gnu/qt5/QtGui/5.6.1/QtGui/qpa/qplatformintegrationfactory_p.h

symbol define please check: https://github.com/linuxdeepin/deepin-tool-kit/blob/eb3568c486ee99ccbdd0cd65936e96c140a33696/dwidget/widgets/dapplication.cpp

**Comment by PikachuHy** [comment]
ok, thanks
