### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by jakubiszon26** [linuxdeepin/deepin-system-monitor#50]
Cannot read /home/jakub/Apps/deepin-system-monitor: file to open is a directory
Error processing project file: ..

**Comment by MouadBH** [comment]
i face same problem.

**Comment by LeiYu-uniontech** [comment]
> 无法读取/ home / jakub / Apps / deepin-system-monitor：要打开的文件是目录
> 处理项目文件时出错：..

Can you give me more detailed information? No limitation on screenshots or replay process

**Comment by LeiYu-uniontech** [comment]
> Cannot read /home/jakub/Apps/deepin-system-monitor: file to open is a directory
> Error processing project file: ..

Could you give me more details? Take screenshots or reproduce the process

**Comment by ZhangZJ-Github** [comment]
The same problem +1.

**Comment by iononi** [comment]
The same problem +1
