### ISSUE TITLE
[Feature Request]  - Allow to select multiple proccesses

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-system-monitor#52]
Let's say your Windows game has crashed and you'd like to end all wine processes. In this case, you have to go selectively through every single process and press alt+e on each of them to shut everything down.

I would appreciate a functionality that allows selecting all processes matching given criteria by pressing CTRL+A similarly while managing a text.(like all processes which have .exe in their name like example below) 
 
![image](https://user-images.githubusercontent.com/39202451/112729980-2dd37600-8f2f-11eb-8673-272abef46f39.png)

**Comment by YutianGe** [comment]
Thank you for your suggestion. We will consider it carefully
