### ISSUE TITLE
Monitor Network Tracking Issue

### ISSUE THREAD

**Issue by Noorullah-Ahmadzai** [linuxdeepin/deepin-system-monitor#53]
## Monitor Network Tracking Issue

Deepin Monitor Tracks the localhost (127.0.0.1) which is really confusing for me as a user and a web developer!

- I usually reload my browser a lot.
- The data served from localhost is also tracked with it.

I downloaded almost 50 MB of data but it shows me around 450 MB download. More than 400 is traced via `Localhost`
![image](https://user-images.githubusercontent.com/28804764/113440299-68db1b00-9401-11eb-9dfb-0e03403f8b9d.png)

**Comment by LeiYu-uniontech** [comment]
This shows the total data since the boot, you can refer to "ifconfig".
