### ISSUE TITLE
Inaccurate Download/Upload speeds 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-system-monitor#54]
By an accident I just found out that system monitor gives inaccurate readings of your internet speed. There is no chance my bandwidth is able to excel 4.0MB/s

https://user-images.githubusercontent.com/39202451/113468755-7798f080-9448-11eb-801f-e2f80eeb40b5.mp4

**Comment by LeiYu-uniontech** [comment]
This phenomenon is normal. You can try other application software to test whether the download speed exceeds 4.0  MB/s

**Comment by vesterlay** [comment]
I redid comparison with NetHogs and there were no issues. It did not exceed 4.0MB/s. It's just system monitor which sometimes multiplies the current speed by 2 for some reason. I guess it's not such a big deal actually, you can close this issue if this behaviour is anticipated.

**Comment by vesterlay** [comment]
Alright, there is no way this is a normal behavior

https://user-images.githubusercontent.com/39202451/113825177-efd12000-9780-11eb-9f61-8d8f975b5d78.mp4

**Comment by YutianGe** [comment]
We've done some more optimizations, so you can try it with the latest code
