### ISSUE TITLE
[Bug] Frequency doesn't display correctly with translation 

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/deepin-system-monitor#61]
Applying any translation other than English results in displaying incorrect values. 

![image](https://user-images.githubusercontent.com/39202451/145275044-fd64d25b-a9ec-4d6f-8baa-7ccdbabfe4be.png)
It should be 0.00MHz ~ 4.50MHz
Everything works correctly when I switch to English

**Comment by yorcan** [comment]
Hi there,it has been fixed in maintain/1042 && dev/1050 of branches,should be pull the new code and checkout it .
![Bez nazwy](https://user-images.githubusercontent.com/22020323/148315765-27d315e1-23d6-4228-a9ce-e1a4c44095ba.png)



> Applying any translation other than English results in displaying incorrect values.
> 
> ![image](https://user-images.githubusercontent.com/39202451/145275044-fd64d25b-a9ec-4d6f-8baa-7ccdbabfe4be.png) It should be 0.00MHz ~ 4.50MHz Everything works correctly when I switch to English

**Comment by raspin0** [comment]
Thank you for the fix. Issue has been solved in Deepin 20.04
