### ISSUE TITLE
ERROR: opening handler for device wlp7s0

### ISSUE THREAD

**Issue by PikachuHy** [linuxdeepin/deepin-system-monitor#7]
after i compile deepin-system-monitor,then run ./deepin-system-monitor 
```
load translate "/usr/share/dtkwidget/translations/dtkwidget_zh_CN"
"deepin-system-monitor" can not find qm files
ERROR: opening handler for device wlp7s0: 
```
run sudo ./deepin-system-monitor 
```
load translate "/usr/share/dtkwidget/translations/dtkwidget_zh_CN"
"deepin-system-monitor" can not find qm files
Ethernet link detected
```
oh my god

**Comment by manateelazycat** [comment]
Read https://github.com/linuxdeepin/deepin-system-monitor/blob/master/README.md
You should use setcap give system monitor authority:

sudo setcap cap_kill,cap_net_raw,cap_dac_read_search,cap_sys_ptrace+ep ./deepin-system-monitor

Never use sudo with deepin-system-monitor
